manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kumamod
      url-base: https://github.com/kumamod
    - name: caksoylar
      url-base: https://github.com/caksoylar
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: kumamod
      revision: c9ab9a3f
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: e9472d6c
  self:
    path: config
